title = "John Duong"
baseURL = "https://johnduong.com/"
languageCode = "en-us"
theme = "ananke"
#themesDir = "../.."
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true

[languages]
  [languages.en]
    title = "John Duong"
    weight = 1
    contentDir = "content/en"
  #[languages.fr]
    #title = "Mon blogue"
   # weight = 2
   # contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "John Duong's Portfolio Website"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/JohnDuongOC"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/johntanduong/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  tiktok = ""

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
